package edu.asu.cse360.team25.protocol;

public enum DoctorServerMsg {

	NONE,
	
	LOGIN,
	LOGIN_ACK,
	LOGOUT,
	LOGOUT_ACK,
	
//	QUERY_CASE_LIST,
//	QUERY_CASE_LIST_ACK,

	QUERY_PATIENT_PROFILE,
	QUERY_PATIENT_PROFILE_ACK,
	QUERY_ALL_CASE_ID_OF_ONE_PATIENT,
	QUERY_ALL_CASE_ID_OF_ONE_PATIENT_ACK,
	QUERY_CASE,
	QUERY_CASE_ACK,
	QUERY_ALL_LAB_MEASUREMENT_ID_OF_ONE_PATIENT,
	QUERY_ALL_LAB_MEASUREMENT_ID_OF_ONE_PATIENT_ACK,
	QUERY_LAB_MEASUREMENT,
	QUERY_LAB_MEASUREMENT_ACK,
	QUERY_CHAT_HISTORY,
	QUERY_CHAT_HISTORY_ACK,

	FORWARD_HANDLE_CASE, // send by server
	FORWARD_HANDLE_CASE_ACK,
	
	LINK_CASE_TO_CURRENT_CASE,
	LINK_CASE_TO_CURRENT_CASE_ACK,
	LINK_LAB_MEASUREMENT_TO_CURRENT_CASE,
	LINK_LAB_MEASUREMENT_TO_CURRENT_CASE_ACK,
	
	CHAT_MESSAGE,
	FORWARD_CHAT_MESSAGE, // send by server

	FORWARD_SUSPEND_CASE_BY_PATIENT, // send by server
	FORWARD_SUSPEND_CASE_BY_PATIENT_ACK,
	SUSPEND_CASE_BY_DOCTOR,
	SUSPEND_CASE_BY_DOCTOR_ACK,
	FINISH_CASE,
	FINISH_CASE_ACK;
	
}
