package edu.asu.cse360.team25.protocol;

public enum PatientServerMsg {

	NONE,
	
	REGISTER,
	REGISTER_ACK,
	LOGIN,
	LOGIN_ACK,
	LOGOUT,
	LOGOUT_ACK,

	QUERY_PATIENT_PROFILE,
	QUERY_PATIENT_PROFILE_ACK,
	UPDATE_PATIENT_PROFILE,
	UPDATE_PATIENT_PROFILE_ACK,
	QUERY_DOCTOR_LIST,
	QUERY_DOCTOR_LIST_ACK,
	QUERY_CASE_LIST,
	QUERY_CASE_LIST_ACK,
	QUERY_CHAT_HISTORY,
	QUERY_CHAT_HISTORY_ACK,

	CREATE_CASE,
	CREATE_CASE_ACK, // send by doctor-server connection
	RESUME_CASE,
	RESUME_CASE_ACK,
	
	CHAT_MESSAGE,
	FORWARD_CHAT_MESSAGE, // send by server
	
	SUSPEND_CASE_BY_PATIENT,
	SUSPEND_CASE_BY_PATIENT_ACK,
	FORWARD_SUSPEND_CASE_BY_DOCTOR, // send by server
	FORWARD_SUSPEND_CASE_BY_DOCTOR_ACK,
	FORWARD_FINISH_CASE, // send by server
	FORWARD_FINISH_CASE_ACK;
	
}
